set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_BINARY_DIR};${CMAKE_PROJECT_NAME};ALL;/")
set(CPACK_PACKAGE_CONTACT "contact@quasardb.net")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "quasardb is an advanced, distributed, high-performance key-value store")
set(CPACK_PACKAGE_NAME "qdb-${QDB_VERSION}")
set(CPACK_PACKAGE_VENDOR "quasardb SAS")
set(CPACK_PACKAGE_VERSION ${QDB_VERSION})

if(WIN32)
    set(CPACK_GENERATOR "ZIP")
else()
    set(CPACK_GENERATOR "TGZ")
endif()

string(TOLOWER
    qdb-${QDB_VERSION}-${CMAKE_SYSTEM_NAME}-${QDB_CPU_ARCH}
    CPACK_PACKAGE_INSTALL_DIRECTORY)

string(TOLOWER qdb-${QDB_VERSION}-${CMAKE_SYSTEM_NAME}-${QDB_CPU_ARCH} CPACK_PACKAGE_FILE_NAME)

include(CPack)
