# are we compiling 32-bit or 64-bit?
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(QDB_CPU_ARCH "32bit")
    set(QDB_CPU_ARCH_IS_32BIT ON)
else()
    set(QDB_CPU_ARCH "64bit")
    set(QDB_CPU_ARCH_IS_64BIT ON)
endif()

if("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "arm"
        OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "aarch64"
        OR "${CMAKE_SYSTEM_PROCESSOR}" MATCHES "cortex"
        OR CMAKE_GENERATOR MATCHES "ARM")
    set(QDB_CPU_IS_ARM ON)
elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86"
        OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64"
        OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "AMD64" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "amd64")
    set(QDB_CPU_IS_X86 ON)
else()
    message(FATAL_ERROR "Unknown CMAKE_SYSTEM_PROCESSOR = ${CMAKE_SYSTEM_PROCESSOR}")
endif()

if(QDB_CPU_ARCHITECTURE_CORE2)
    set(QDB_CPU_ARCH "${QDB_CPU_ARCH}-core2")
elseif(QDB_CPU_IS_ARM)
    set(QDB_CPU_ARCH "${QDB_CPU_ARCH}-${CMAKE_SYSTEM_PROCESSOR}")
endif()
