add_compile_options(
    -DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
    -DBOOST_MPL_LIMIT_LIST_SIZE=60
    -DBOOST_MPL_LIMIT_SET_SIZE=30
    -DBOOST_MPL_LIMIT_VECTOR_SIZE=30
    -DBOOST_RESULT_OF_USE_DECLTYPE
    -DBOOST_SPIRIT_USE_PHOENIX_V3
    -DFUSION_MAX_VECTOR_SIZE=20
    -DBOOST_ASIO_NO_THROW=1
    -DBOOST_THREAD_DONT_PROVIDE_DEPRECATED_FEATURES_SINCE_V3_0_0=1

    -DRAPIDJSON_HAS_STDSTRING=1
    -DRAPIDJSON_HAS_CXX11_RVALUE_REFS=1

    -DTBB_IMPLEMENT_CPP0X=0
    -DTBB_PREVIEW_MEMORY_POOL=1

    $<$<NOT:$<CONFIG:Debug>>:-DNDEBUG>
    $<$<CONFIG:Debug>:-DDEBUG=1>
    $<$<CONFIG:Debug>:-D_DEBUG=1>
)

if(MSVC)
    add_definitions(
        /DBOOST_ALL_NO_LIB

        /D__TBB_NO_IMPLICIT_LINKAGE=1
        /D__TBBMALLOC_NO_IMPLICIT_LINKAGE=1

        /D_WINDOWS
        /DWIN32
        /DWIN32_LEAN_AND_MEAN

        /DWINVER=0x0600
        /D_WIN32_WINNT=0x0600
        /DNTDDI_VERSION=0x06000000
        /DBOOST_USE_WINAPI_VERSION=0x0600

        /DNOMINMAX=1
        /D_CRT_SECURE_NO_DEPRECATE
        /D_CRT_SECURE_NO_WARNINGS
        /D_SCL_SECURE_NO_WARNINGS
        /D_SECURE_SCL=$<CONFIG:Debug>
        /D_HAS_ITERATOR_DEBUGGING=$<CONFIG:Debug>
        /D_ENABLE_ATOMIC_ALIGNMENT_FIX

        /DRAPIDJSON_HAS_STDSTRING=1
        /DRAPIDJSON_HAS_CXX11_RVALUE_REFS=1
    )
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    add_compile_options(
        -DPIC
    )
endif()

if(CMAKE_COMPILER_IS_GNUCXX)
    add_compile_options(
        -DPIC
        $<$<CONFIG:Debug>:-D_GLIBCXX_DEBUG=1>
        -DBOOST_NO_AUTO_PTR
    )
endif()

add_compile_options(
    $<$<CONFIG:Debug>:-DQDB_BUILD_TYPE_DEBUG=1>
    $<$<CONFIG:Release>:-DQDB_BUILD_TYPE_RELEASE=1>
    $<$<CONFIG:RelWithDebInfo>:-DQDB_BUILD_TYPE_RELWITHDEBINFO=1>
    $<$<CONFIG:Sanitize>:-DQDB_BUILD_TYPE_SANITIZE=1>
    $<$<CONFIG:SanitizeValgrind>:-DQDB_BUILD_TYPE_SANITIZE_VALGRIND=1>
)
